packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.19.0
    '@antfu/ni': ^24.4.0
    bumpp: ^10.4.0
    eslint: ^9.39.2
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.1
    tsdown: ^0.11.13
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^6.4.1
  config:
    cac: ^6.7.14
    unconfig: ^7.4.2
    zod: ^3.25.76
  ethereum:
    '@nomicfoundation/hardhat-ignition': ^3.0.7
    '@nomicfoundation/hardhat-ignition-viem': ^3.0.7
    '@nomicfoundation/hardhat-keystore': 3.0.0-next.8
    '@nomicfoundation/hardhat-toolbox-viem': 4.0.0-next.7
    '@typechain/ethers-v6': ^0.5.1
    ethers: ^6.16.0
    forge-std: github:foundry-rs/forge-std#v1.9.4
    hardhat: 3.0.0-next.7
    typechain: ^8.3.2
    viem: ^2.45.1
    wagmi: ^2.19.5
  inlined:
    '@antfu/utils': ^9.3.0
  react:
    '@types/react': ^19.2.10
  runtime:
    '@hairy/utils': ^1.47.0
    '@types/fs-extra': ^11.0.4
    change-case: ^5.4.4
    dedent: ^1.7.1
    fs-extra: ^11.3.3
    glob: ^11.1.0
    knitwork-x: ^0.2.0
    nanoid: ^5.1.6
    nanospinner: ^1.2.2
    picocolors: ^1.1.1
  skills:
    skills: ^1.3.3
    skills-manifest: ^0.3.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^22.19.8
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
