packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@hairy/utils': ^1.30.0
  '@nomicfoundation/hardhat-ignition': ^3.0.0-next.8
  '@nomicfoundation/hardhat-ignition-viem': ^3.0.0-next.8
  '@nomicfoundation/hardhat-keystore': 3.0.0-next.8
  '@nomicfoundation/hardhat-toolbox-viem': 4.0.0-next.7
  '@typechain/ethers-v6': ^0.5.1
  '@types/fs-extra': ^11.0.4
  c12: ^3.0.3
  cac: ^6.7.14
  change-case: ^5.4.4
  dedent: ^1.6.0
  ethers: ^6.14.1
  forge-std: github:foundry-rs/forge-std#v1.9.4
  fs-extra: ^11.3.0
  glob: ^11.0.2
  hardhat: 3.0.0-next.7
  nanospinner: ^1.2.2
  picocolors: ^1.1.1
  typechain: ^8.3.2
  viem: ^2.29.4
  zod: ^3.24.4
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsdown: ^0.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
