/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  createWatchContractEvent,
  createWatchContractEventBy,
  createGetContract,
  createGetContractBy,
  createReadContract,
  createWriteContract,
  createReadContractBy,
  createWriteContractBy,
  createUseContract,
  createUseContractBy,
} from './library'
import { erc20Abi, erc721Abi, addresses } from './config'
export { erc20Abi, erc721Abi } from './config'

export { SubscribeWagmiConfig } from './library'
export {
  addresses,
  chain,
  chains,
  client,
  wallet,
} from './config'

import {
  createUseReadContract,
  createUseSimulateContract,
  createUseWatchContractEvent,
  createUseWriteContract,
} from 'wagmi/codegen'

export const getContract = createGetContract()
export const useContract = createUseContract()

export const getErc20 = createGetContractBy(erc20Abi)
export const useErc20 = createUseContractBy(erc20Abi)
export const erc20Address = Reflect.get(addresses, 'ERC20')

export const watchErc20Event = createWatchContractEvent(erc20Abi)
export const watchErc20ApprovalEvent = createWatchContractEventBy(erc20Abi, 'Approval')
export const watchErc20TransferEvent = createWatchContractEventBy(erc20Abi, 'Transfer')

export const useWatchErc20Event = createUseWatchContractEvent({ abi: erc20Abi, address: erc20Address })
export const useWatchErc20ApprovalEvent = createUseWatchContractEvent({ abi: erc20Abi, address: erc20Address, eventName: 'Approval' })
export const useWatchErc20TransferEvent = createUseWatchContractEvent({ abi: erc20Abi, address: erc20Address, eventName: 'Transfer' })

export const readErc20 = createReadContract(erc20Abi)
export const useReadErc20 = createUseReadContract({ abi: erc20Abi, address: erc20Address })

export const readErc20Allowance = createReadContractBy(erc20Abi, 'allowance')
export const readErc20BalanceOf = createReadContractBy(erc20Abi, 'balanceOf')
export const readErc20Decimals = createReadContractBy(erc20Abi, 'decimals')
export const readErc20Name = createReadContractBy(erc20Abi, 'name')
export const readErc20Symbol = createReadContractBy(erc20Abi, 'symbol')
export const readErc20TotalSupply = createReadContractBy(erc20Abi, 'totalSupply')

export const useReadErc20Allowance = createUseReadContract({ abi: erc20Abi, address: erc20Address, functionName: 'allowance' })
export const useReadErc20BalanceOf = createUseReadContract({ abi: erc20Abi, address: erc20Address, functionName: 'balanceOf' })
export const useReadErc20Decimals = createUseReadContract({ abi: erc20Abi, address: erc20Address, functionName: 'decimals' })
export const useReadErc20Name = createUseReadContract({ abi: erc20Abi, address: erc20Address, functionName: 'name' })
export const useReadErc20Symbol = createUseReadContract({ abi: erc20Abi, address: erc20Address, functionName: 'symbol' })
export const useReadErc20TotalSupply = createUseReadContract({ abi: erc20Abi, address: erc20Address, functionName: 'totalSupply' })

export const writeErc20 = createWriteContract(erc20Abi)
export const writeErc20Approve = createWriteContractBy(erc20Abi, 'approve')
export const writeErc20Transfer = createWriteContractBy(erc20Abi, 'transfer')
export const writeErc20TransferFrom = createWriteContractBy(erc20Abi, 'transferFrom')

export const useWriteErc20 = createUseWriteContract({ abi: erc20Abi, address: erc20Address })
export const useWriteErc20Approve = createUseWriteContract({ abi: erc20Abi, address: erc20Address, functionName: 'approve' })
export const useWriteErc20Transfer = createUseWriteContract({ abi: erc20Abi, address: erc20Address, functionName: 'transfer' })
export const useWriteErc20TransferFrom = createUseWriteContract({ abi: erc20Abi, address: erc20Address, functionName: 'transferFrom' })

export const useSimulateErc20 = createUseSimulateContract({ abi: erc20Abi, address: erc20Address })
export const useSimulateErc20Approve = createUseSimulateContract({ abi: erc20Abi, address: erc20Address, functionName: 'approve' })
export const useSimulateErc20Transfer = createUseSimulateContract({ abi: erc20Abi, address: erc20Address, functionName: 'transfer' })
export const useSimulateErc20TransferFrom = createUseSimulateContract({ abi: erc20Abi, address: erc20Address, functionName: 'transferFrom' })
